language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
install: composer install
script: vendor/bin/phpunit --coverage-clover clover.xml
after_script: vendor/bin/php-coveralls --coverage_clover=clover.xml -v
